Move chktty to bin

diff --git a/menuapp/bin/chktty b/menuapp/bin/chktty
--- a/menuapp/bin/chktty
+++ b/menuapp/bin/chktty
@@ -3,10 +3,15 @@
 #
 # Before using this script, set TTYPATH for your system
 #
-if [ -z "$TTYPATH" ]; then
-	echo "Please set TTYPATH for your system in this script"
-	echo "or set TTYPATH in the environment before running this script."
-	exit 1
+TTYPATH="$(dirname "$(tty)")"
+if [ ! -d "$TTYPATH" ]; then
+    echo
+    echo This script believes "$TTYPATH" is the directory in which your tty
+    echo devices are located, but no directory was found at that location.
+    echo Please set the variable, TTYPATH echo to the correct directory in your
+    echo environment or in this script.
+    echo
+    exit 1
 fi
 # For example, on Linux systems, you might set:
 # TTYPATH=/dev/pts
@@ -26,46 +31,45 @@ fi
 # Usage: chktty terminal-number [-r to create reference]
 #
 if [ $# -lt 1 ]; then
-	echo usage: "$0" terminal-number [-r to create reference] [optional file extension prefix]
-	exit 1
+    echo usage: "$0" terminal-number [-r to create reference] [optional file extension prefix]
+    exit 1
 fi
-TTYPATH=/dev/pts
 tty_num="$1"
 tty_dev="$TTYPATH/$tty_num"
 if [ ! -e "$tty_dev" ]; then
-	echo "$tty_dev does not exist"
-	exit 1
+    echo "$tty_dev does not exist"
+    exit 1
 fi
 shift
 mkref=0
 if [ $# -gt 0 ] && [ "$1" = "-r" ]; then
-	mkref="1"
-	shift
+    mkref="1"
+    shift
 fi
 if [ $# -gt 0 ] && [ "$1" != "" ]; then
-	ext="$1.ref"
+    ext="$1.ref"
 else
-	ext="ref"
+    ext="ref"
 fi
 ref_file="$CMENU_HOME"/test/tty/stty."$ext"
 if [ "$mkref" = "1" ]; then
-	echo "Creating reference stty settings in" "$ref_file"
-	mkdir -p "$CMENU_HOME"/test/tty
-	echo stty."$ext" >"$ref_file"
-	stty -a <"$tty_dev" | sed 's/ = /=/g
+    echo "Creating reference stty settings in" "$ref_file"
+    mkdir -p "$CMENU_HOME"/test/tty
+    echo stty."$ext" >"$ref_file"
+    stty -a <"$tty_dev" | sed 's/ = /=/g
 s/speed /speed~/
 s/rows /rows~/
 s/columns /columns~/
 s/\s*$//
 s/;//g' | tr ' ' '\n' | tr '~' ' ' >>"$ref_file"
-	stty -g <"$tty_dev" >"$ref_file".g
-	exit 0
+    stty -g <"$tty_dev" >"$ref_file".g
+    exit 0
 fi
 if [ ! -e "$ref_file" ]; then
-	echo "Reference file" "$ref_file" "not found!"
-	echo "Create reference by running:"
-	echo "$0 terminal-number -r"
-	exit 1
+    echo "Reference file" "$ref_file" "not found!"
+    echo "Create reference by running:"
+    echo "$0 terminal-number -r"
+    exit 1
 fi
 echo "Comparing tty" "$tty_dev" "to reference" "$ref_file"
 chk_file="$CMENU_HOME"/test/tty/stty"$tty_num".a
@@ -80,22 +84,22 @@ s/;//g' | tr ' ' '\n' | tr '~' ' ' >>"$chk_file"
 diff -W40 -y --suppress-common-lines "$ref_file" "$chk_file" >"$diff_file"
 lines=$(wc -l "$diff_file" | awk '{print $1}')
 if [ "$lines" -eq 1 ]; then
-	echo "No differences found."
-	rm -f "$chk_file" "$diff_file"
+    echo "No differences found."
+    rm -f "$chk_file" "$diff_file"
 else
-	echo "Differences found!"
-	cat "$diff_file"
-	echo Would you like to use "stty" "$ref_file".g "to fix settings?"
-	a=$(enterchr "Apply reference settings to $tty_dev (y/n)?")
-	if [ "$a" != "y" ] && [ "$a" != "Y" ]; then
-		echo
-		echo "Not applying settings."
-		exit 0
-	fi
-	echo
-	echo "Applying reference settings to" "$tty_dev"
-	settings=$(cat "$ref_file".g)
-	echo "stty $settings <$tty_dev"
-	stty "$settings" <"$tty_dev"
-	echo "Done! At your command, Master."
+    echo "Differences found!"
+    cat "$diff_file"
+    echo Would you like to use "stty" "$ref_file".g "to fix settings?"
+    a=$(enterchr "Apply reference settings to $tty_dev (y/n)?")
+    if [ "$a" != "y" ] && [ "$a" != "Y" ]; then
+        echo
+        echo "Not applying settings."
+        exit 0
+    fi
+    echo
+    echo "Applying reference settings to" "$tty_dev"
+    settings=$(cat "$ref_file".g)
+    echo "stty $settings <$tty_dev"
+    stty "$settings" <"$tty_dev"
+    echo "Done! At your command, Master."
 fi
